default_stages: [pre-commit]

repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.98.0"
    hooks:
      - id: terraform_fmt
        args: [recursive]
        working-dir: infra
