spring:
  config:
    activate:
      on-profile: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://cognito-idp.${AWS_REGION:ap-northeast-1}.amazonaws.com/${COGNITO_USER_POOL_ID}"
app:
  security:
    cognito:
      client-id: ${COGNITO_CLIENT_ID}
      base-uri: "https://${COGNITO_DOMAIN}.auth.${AWS_REGION:ap-northeast-1}.amazoncognito.com"
