spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://cognito-idp.${AWS_REGION:ap-northeast-1}.amazonaws.com/${COGNITO_USER_POOL_ID:ap-northeast-1_example}"
app:
  security:
    cognito:
      client-id: ${COGNITO_CLIENT_ID}
