spring:
  main:
    banner-mode: off
    web-application-type: servlet
    lazy-initialization: true
logging:
  level:
    org.springframework: INFO
    org.springframework.boot.autoconfigure: WARN
    com.amazonaws.serverless: INFO
    com.github.moriakira.jibundashboard.resource: INFO
