name: Continuous Integration - Backend
on:
  push:
    branches:
      - main
    paths:
      - "back/**"
      - ".github/workflows/ci-back.yaml"

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'gradle'

      - name: Make Gradle Wrapper Executable
        run: sudo chmod +x gradlew

      - name: Check Code
        run: ./gradlew detekt spotlessCheck test  --no-daemon
