name: Continuous Integration - Back
on:
  push:
    branches:
      - main
    paths:
      - "back/**"
      - ".github/workflows/ci-back.yaml"

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Detekt (linter)
        run: ./gradlew detekt --no-daemon

      - name: Spotless Check (format)
        run: ./gradlew spotlessCheck --no-daemon

      - name: Test
        run: ./gradlew test --no-daemon
